### ISSUE TITLE
<HTTPError 401: 'Unauthorized'> Failed on Attachment creation. Trying again.

### ISSUE THREAD

**Issue by GiorgioBart** [wiltonsr/Trello2Kanboard#4]
Getting:
<HTTPError 401: 'Unauthorized'>
Failed on Attachment creation. Trying again.

When importing trello.json to Kanboard gets this error.
It's like we need to authenticate against Trello to download attachment referenced in the json file.

**Comment by wiltonsr** [comment]
Hi @GiorgioBart 

Currently the attachment download functionality is not working correctly. Just the attachment link is no longer enough to download the file from Trello. It is necessary to use the API and the tool does not support this functionality for now.

You can use the plugin [TrelloJSON2Kanboard](https://github.com/wiltonsr/TrelloJSON2Kanboard) instead of this tool, it will be created a comment with the attachment link.
